# Generated by Django 4.0.6 on 2022-07-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comment_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='writer',
        ),
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=models.TextField(verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='이미지 첨부'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=200, verbose_name='제목'),
        ),
    ]
