# Generated by Django 4.0.6 on 2022-07-14 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_blog_writer_alter_blog_body_alter_blog_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='type',
            field=models.CharField(blank=True, choices=[('Etc', 'Etc'), ('Dog', 'Dog'), ('Cat', 'Cat')], max_length=5, null=True),
        ),
    ]
